# Week-2

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dff = pd.read_csv('/kaggle/input/sample-dataset/SampleSuperstore.csv')
dff

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,25.2480,3,0.20,4.1028
9990,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,91.9600,2,0.00,15.6332
9991,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,258.5760,2,0.20,19.3932
9992,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,29.6000,4,0.00,13.3200
9993,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,243.1600,2,0.00,72.9480

In [3]:
print(dff.columns)  # i just checked columns just to easy for me

Index(['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Postal Code',
       'Region', 'Category', 'Sub-Category', 'Sales', 'Quantity', 'Discount',
       'Profit'],
      dtype='object')

In [4]:
dff.head()  # first five rows from data frame

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164

# Create Synthetic Date Column¶

In [5]:
print(dff['Date'].head())

KeyError: 'Date'

In [ ]:
dff['Date'] = pd.date_range(start='2023-01-01', periods=len(dff), freq='D')

In [ ]:
print(dff.columns)

In [ ]:
# Remove any hidden spaces from column names
dff.rename(columns=lambda x: x.strip(), inplace=True)
print('Date' in dff.columns)  # Should print True

In [ ]:
dff.set_index('Date', inplace=True)
print(dff.head())

# Aggregate Sales Monthly

In [ ]:
monthly_sales = dff['Sales'].resample('M').sum()   #“Sales were aggregated monthly using pandas resample with Month-End frequency to analyze trends over time.”
print(monthly_sales.head())

# Line Chart – Monthly Sales Trend

In [ ]:
plt.figure()                 # Line chart showing monthly sales trend over time.
monthly_sales.plot()         # X-axis: Months, Y-axis: Total Sales.
plt.title("Monthly Sales Trend")   # This visualization highlights trends and patterns in sales over the months.
plt.xlabel("Month")
plt.ylabel("Total Sales")
plt.grid(True)
plt.tight_layout()
plt.savefig("monthly_sales_trend.png")
plt.show()

# Bar Chart – Sales by Category

In [ ]:
category_sales = dff.groupby('Category')['Sales'].sum()    # Category sales

plt.figure()
category_sales.plot(kind='bar')
plt.title("Sales by Category")
plt.xlabel("Category")
plt.ylabel("Total Sales")
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig("category_sales_bar.png")
plt.show()

## Pie Chart – Sales Share by Category

In [ ]:
plt.figure()       #Helps identify dominant category
category_sales.plot(kind='pie', autopct='%1.1f%%', startangle=90)
plt.title("Sales Share by Category")
plt.ylabel("")
plt.tight_layout()
plt.savefig("category_sales_pie.png")
plt.show()

# A Short description
Monthly sales trends were visualized using a line chart after aggregating sales data by month. Bar charts were used to compare total sales across product categories, revealing relative performance. A pie chart illustrated the percentage share of each category in total sales. All charts include proper labels and formatting for clarity.